{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dome-ied.redis.fullname" . }}
  labels:
    {{- include "dome-ied.redis.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "dome-ied.redis.serviceName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "dome-ied.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dome-ied.redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ include "dome-ied.redis.image" . }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - redis-server
            {{- if .Values.redis.auth.enabled }}
            - --requirepass
            - $(REDIS_PASSWORD)
            {{- end }}
            - --appendonly
            - "yes"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- if .Values.redis.auth.enabled }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.auth.existingSecret | default (printf "%s-redis" (include "dome-ied.fullname" .)) }}
                  key: redis-password
          {{- end }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                {{- if .Values.redis.auth.enabled }}
                - -a
                - $(REDIS_PASSWORD)
                {{- end }}
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                {{- if .Values.redis.auth.enabled }}
                - -a
                - $(REDIS_PASSWORD)
                {{- end }}
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | quote }}
  {{- else }}
  volumes:
    - name: data
      emptyDir: {}
  {{- end }}
{{- end }}
